name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Use the EC2 SSH key secret

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.53.125.141 << 'EOF'
            # Ensure the application directory exists
            mkdir -p /home/ubuntu/my-nodejs-app
            cd /home/ubuntu/my-nodejs-app

            # Install Node.js and PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing..."
              npm install -g pm2
            fi

            # If it's not a git repository, initialize it and set the remote
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:mjavason/AWS-CI-CD-Demo.git
            fi

            # Fetch and reset the repository
            git fetch origin
            git reset --hard origin/main

            # Install Node.js dependencies
            npm install

            # Restart the app using PM2
            pm2 restart app || pm2 start npm --name "app" -- start
          EOF
