name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Use the EC2 SSH key secret

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.53.125.141 << 'EOF'
            cd /home/ubuntu/my-nodejs-app

            # If it's not a git repository, initialize it and set the remote
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:mjavason/AWS-CI-CD-Demo.git
            fi

            # Pull the latest changes from GitHub
            git fetch origin
            git reset --hard origin/main  # Ensure the local repo matches the remote exactly

            # Install dependencies
            npm install

            # Restart the app using pm2 (or your preferred method)
            pm2 restart app
          EOF
