name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch (adjust if you're using a different branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.53.125.141 << 'EOF'
            
            git pull origin main
            npm install
            npm run start  # If using pm2 to manage your app (you can change it to your app's start command)
          EOF
