name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for GitHub repository access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.53.125.141 << 'EOF'
            cd /home/ubuntu

            # Clone the repo using SSH URL
            # if [ ! -d "my-nodejs-app" ]; then
              git clone git@github.com:mjavason/AWS-CI-CD-Demo.git my-nodejs-app
            # fi

            cd my-nodejs-app
            git pull origin main
            npm install
            pm2 restart app
          EOF
